"""whatever

Revision ID: 0e83dc55e73b
Revises: de47c83b792f
Create Date: 2026-04-27 15:11:53.763910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0e83dc55e73b"
down_revision: Union[str, Sequence[str], None] = "de47c83b792f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradition", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("number_of_included_sections", sa.Integer(), nullable=False)
        )
        batch_op.drop_column("ref")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradition", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ref", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("number_of_included_sections")

    # ### end Alembic commands ###
