"""rename resource_id to collection_id

Revision ID: 2a41a8e9582e
Revises: bfd55d461230
Create Date: 2026-04-14 10:58:15.169119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a41a8e9582e'
down_revision: Union[str, Sequence[str], None] = 'bfd55d461230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('job', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('resource_id', sa.VARCHAR(), nullable=False))
    op.drop_column('job', 'collection_id')
    # ### end Alembic commands ###
