"""Make schema agnostic

Revision ID: 8b244e131ae5
Revises: e363b8d84258
Create Date: 2026-05-08 15:46:31.348329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8b244e131ae5"
down_revision: Union[str, Sequence[str], None] = "e363b8d84258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "collection_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.drop_column("collection_id")
        batch_op.drop_column("dts_base_url")

    with op.batch_alter_table("tradition", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "collection_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.drop_column("dts_base_url")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tradition", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "dts_base_url",
                sa.VARCHAR(),
                server_default=sa.text("'http://ftsr-dev.unil.ch:8000'"),
                nullable=False,
            )
        )
        batch_op.drop_column("collection_url")

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "dts_base_url",
                sa.VARCHAR(),
                server_default=sa.text("'http://ftsr-dev.unil.ch:8000'"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("collection_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("collection_url")

    # ### end Alembic commands ###
