"""rename resource_id to collection_id

Revision ID: bfd55d461230
Revises: 960cadde2ef4
Create Date: 2026-04-14 10:42:58.751843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfd55d461230'
down_revision: Union[str, Sequence[str], None] = '960cadde2ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradition', sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tradition', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradition', sa.Column('resource_id', sa.VARCHAR(), nullable=False))
    op.drop_column('tradition', 'collection_id')
    # ### end Alembic commands ###
