"""remove smart_det from job

Revision ID: c6c57c77902b
Revises: 1d3bad039d50
Create Date: 2026-08-18 14:14:16.171341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6c57c77902b'
down_revision: Union[str, Sequence[str], None] = '1d3bad039d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('smart_det')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_det', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=True))

    # ### end Alembic commands ###
