"""rename resource_id to collection_id

Revision ID: e007adb56a7a
Revises: 2a41a8e9582e
Create Date: 2026-04-14 11:48:15.221687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e007adb56a7a'
down_revision: Union[str, Sequence[str], None] = '2a41a8e9582e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradition', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradition', 'updated_at')
    # ### end Alembic commands ###
