"""Add_dts_base_url

Revision ID: e363b8d84258
Revises: 0e83dc55e73b
Create Date: 2026-04-28 16:37:21.331535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e363b8d84258'
down_revision: Union[str, Sequence[str], None] = '0e83dc55e73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dts_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='http://ftsr-dev.unil.ch:8000'))

    with op.batch_alter_table('tradition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dts_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='http://ftsr-dev.unil.ch:8000'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tradition', schema=None) as batch_op:
        batch_op.drop_column('dts_base_url')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('dts_base_url')

    # ### end Alembic commands ###
