import argparse
import asyncio
import io
import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Dict, Any, List

# Ensure project root is in the Python search path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import httpx
import stanza
import networkx as nx
from cltk import NLP

from core.config import Settings
from services.tei_parser import TEIParser
from services.processors import ClassicalProcessor, ModernProcessor, RawProcessor
from services.converters import EnrichedStrategyConverter, RawStrategyConverter
from services.preparators import DtsPreparator
from helpers.helpers import get_xml_from_dts_url
from clients.collatex_client import CollatexClient
from models.tokenization import CollatexResponse, CollatexWitness

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger("graph_analyzer")


async def fetch_witnesses_xml(
    collection_url: str, ref: str, settings: Settings, http_client: httpx.AsyncClient
) -> Dict[str, str]:
    """
    Resolves collection witness resource URLs for a given reference and downloads their raw XML.
    """
    print(f"\n[DTS] Querying collection resources for reference '{ref}'...")
    success, paths, title, resources = await DtsPreparator.run(
        url=collection_url,
        target_ref=ref,
        job_id=f"graph_analysis_{ref}",
        http_client=http_client,
        settings=settings,
    )
    if not success or not paths:
        raise ValueError(f"DTS preprocessing failed to find reference '{ref}'")

    prep_path = paths[0]
    with open(prep_path, "r", encoding="utf-8") as f:
        prep_data = json.load(f)

    # Clean up the temp pre_collation file generated by the preparator
    try:
        os.remove(prep_path)
    except OSError:
        pass

    xml_cache = {}
    witness_list = prep_data.get("witnesses", [])
    print(f"[DTS] Found {len(witness_list)} witnesses for reference '{ref}'. Downloading XML...")

    for witness in witness_list:
        witness_id = witness["id"]
        content_url = witness["content"]
        xml_data = await get_xml_from_dts_url(content_url, http_client, logger)
        xml_cache[witness_id] = xml_data

    print("[DTS] Successfully fetched and cached XML content.")
    return xml_cache


async def main():
    parser = argparse.ArgumentParser(description="Analyze Variant Graphs from CollateX using NetworkX")
    parser.add_argument(
        "--collection-url",
        default="http://ftsr-dev.unil.ch:8000/api/dts/v1/collection?id=sb-mp",
        help="DTS collection endpoint URL",
    )
    parser.add_argument(
        "--refs",
        default="107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148",
        help="Comma-separated list of DTS references to analyze",
    )
    parser.add_argument(
        "--collatex-url",
        default=None,
        help="Override CollateX server URL",
    )

    args = parser.parse_args()
    settings = Settings()

    collatex_base_url = args.collatex_url or settings.collatex_api_base_url
    refs = [r.strip() for r in args.refs.split(",") if r.strip()]

    print("=" * 80)
    print("σ-BRIDGE VARIANT GRAPH ANALYSIS (NETWORKX)")
    print("=" * 80)
    print(f"Collection URL: {args.collection_url}")
    print(f"References:     {', '.join(refs)}")
    print(f"Pipeline Type:  {settings.pipeline.value}")
    print(f"Language:       {settings.language.value}")
    print(f"CollateX URL:   {collatex_base_url}")
    print("=" * 80)

    # Initialize NLP models
    print("\nInitializing NLP models...")
    nlp_init_start = time.time()
    if settings.pipeline == "modern":
        proc = ModernProcessor(
            stanza.Pipeline(settings.language, processors="tokenize,pos,lemma")
        )
    else:
        proc = ClassicalProcessor(
            NLP(settings.language, backend="stanza", suppress_banner=True)
        )
    print(f"NLP models loaded in {time.time() - nlp_init_start:.2f}s.")

    # Configurations to evaluate
    configs = [
        {
            "name": "Enriched (lemma+pos)",
            "strategy": "enriched",
            "normalization": "lemma+pos",
            "filter_del": True,
        },
        {
            "name": "Enriched (lemma)",
            "strategy": "enriched",
            "normalization": "lemma",
            "filter_del": True,
        },
        {
            "name": "Enriched (text)",
            "strategy": "enriched",
            "normalization": "text",
            "filter_del": True,
        },
        {
            "name": "Raw (text)",
            "strategy": "raw",
            "normalization": "text",
            "filter_del": False,
        },
    ]

    aggregated_results = {}

    async with httpx.AsyncClient(timeout=300.0) as http_client:
        collatex_client = CollatexClient(
            base_url=collatex_base_url, http_client=http_client
        )

        for ref in refs:
            print(f"\n" + "#" * 60)
            print(f"### ANALYZING REFERENCE: {ref}")
            print("#" * 60)

            try:
                xml_cache = await fetch_witnesses_xml(
                    args.collection_url, ref, settings, http_client
                )
            except Exception as e:
                print(f"❌ Error fetching resources for ref '{ref}': {e}")
                continue

            ref_results = []

            for config in configs:
                print(f"\nRunning strategy: {config['name']}...")
                start_time = time.time()

                # Setup the strategy's converter
                if config["strategy"] == "raw":
                    converter = RawStrategyConverter(proc=RawProcessor())
                else:
                    tag_dict = settings.load_tag_dictionary()
                    utils_dir = Path(__file__).parent.parent / "utils"
                    abbr_file = utils_dir / "abbr_classical_greek.csv"
                    parser = TEIParser(abbr_file=str(abbr_file), custom_tags=tag_dict)
                    converter = EnrichedStrategyConverter(proc=proc, parser=parser)

                collatex_witnesses = []
                tokenization_error = False

                for witness_id, xml_content in xml_cache.items():
                    try:
                        tokens = await asyncio.to_thread(
                            converter.run,
                            xml_content,
                            normalization=config["normalization"],
                            filter_del=config["filter_del"],
                        )
                        collatex_witnesses.append(
                            CollatexWitness(id=witness_id, tokens=tokens)
                        )
                    except Exception as e:
                        print(f"  ❌ Tokenization error for '{witness_id}': {e}")
                        tokenization_error = True
                        break

                if tokenization_error or not collatex_witnesses:
                    continue

                # Collate via Collatex requesting GraphML
                payload = CollatexResponse(
                    ref_id=ref, witnesses=collatex_witnesses
                ).model_dump(by_alias=True, exclude_none=True)

                try:
                    graphml_data = await collatex_client.collate(
                        payload=payload, output_format="application/graphml+xml"
                    )
                except Exception as e:
                    print(f"  ❌ Collatex alignment error: {e}")
                    continue

                # Parse GraphML with NetworkX
                try:
                    G = nx.read_graphml(io.BytesIO(graphml_data.encode("utf-8")))
                except Exception as e:
                    print(f"  ❌ NetworkX GraphML parsing error: {e}")
                    continue

                # Compute structural metrics
                num_nodes = G.number_of_nodes()
                num_edges = G.number_of_edges()
                total_tokens = sum(len(w.tokens) for w in collatex_witnesses)
                
                # Merge Ratio: higher means more witness tokens merged into the same graph node
                merge_ratio = total_tokens / num_nodes if num_nodes > 0 else 0
                
                # Variation Points: nodes where paths split (out_degree > 1)
                variation_points = sum(1 for node in G.nodes() if G.out_degree(node) > 1)
                
                elapsed_time = time.time() - start_time

                ref_results.append({
                    "config_name": config["name"],
                    "total_tokens": total_tokens,
                    "nodes": num_nodes,
                    "edges": num_edges,
                    "merge_ratio": round(merge_ratio, 3),
                    "variation_points": variation_points,
                    "time": round(elapsed_time, 2),
                })

                # Accumulate for overall aggregated statistics
                cfg_name = config["name"]
                if cfg_name not in aggregated_results:
                    aggregated_results[cfg_name] = {
                        "total_tokens": 0,
                        "nodes": 0,
                        "edges": 0,
                        "variation_points": 0,
                        "count": 0,
                        "time": 0.0,
                    }
                aggregated_results[cfg_name]["total_tokens"] += total_tokens
                aggregated_results[cfg_name]["nodes"] += num_nodes
                aggregated_results[cfg_name]["edges"] += num_edges
                aggregated_results[cfg_name]["variation_points"] += variation_points
                aggregated_results[cfg_name]["count"] += 1
                aggregated_results[cfg_name]["time"] += elapsed_time

            # Print comparison table for this ref
            print(f"\nVariant Graph Analysis Summary for Reference {ref}:")
            print(
                f"| {'Strategy/Parameter':<25} | {'Tokens':<8} | {'Nodes (V)':<10} | {'Edges (E)':<10} | {'Merge Ratio':<12} | {'Var Points':<11} |"
            )
            print(
                f"|{'-' * 27}|{'-' * 10}|{'-' * 12}|{'-' * 12}|{'-' * 14}|{'-' * 13}|"
            )
            for res in ref_results:
                print(
                    f"| {res['config_name']:<25} "
                    f"| {res['total_tokens']:<8d} "
                    f"| {res['nodes']:<10d} "
                    f"| {res['edges']:<10d} "
                    f"| {res['merge_ratio']:<12.3f} "
                    f"| {res['variation_points']:<11d} |"
                )
            print("-" * 80)

        # Print overall aggregated summary table if analyzing multiple references
        if len(refs) > 1 and aggregated_results:
            summary_lines = []
            summary_lines.append("# Overall Aggregated Variant Graph Summary")
            summary_lines.append("")
            summary_lines.append("======================================================================")
            summary_lines.append("### OVERALL AGGREGATED VARIANT GRAPH SUMMARY (ALL REFERENCES)")
            summary_lines.append("======================================================================")
            summary_lines.append(
                f"| {'Strategy/Parameter':<25} | {'Tokens':<8} | {'Nodes (V)':<10} | {'Edges (E)':<10} | {'Merge Ratio':<12} | {'Var Points':<11} | {'Time':<8} |"
            )
            summary_lines.append(
                f"|{'-' * 27}|{'-' * 10}|{'-' * 12}|{'-' * 12}|{'-' * 14}|{'-' * 13}|{'-' * 10}|"
            )
            for cfg_name, stats in aggregated_results.items():
                tot_tokens = stats["total_tokens"]
                tot_nodes = stats["nodes"]
                merge_ratio = tot_tokens / tot_nodes if tot_nodes > 0 else 0
                tot_time = stats["time"]
                summary_lines.append(
                    f"| {cfg_name:<25} "
                    f"| {tot_tokens:<8d} "
                    f"| {tot_nodes:<10d} "
                    f"| {stats['edges']:<10d} "
                    f"| {merge_ratio:<12.3f} "
                    f"| {stats['variation_points']:<11d} "
                    f"| {tot_time:<7.2f}s |"
                )

            # Print to stdout
            print("\n" + "\n".join(summary_lines[2:]))
            print("=" * 80)

            # Save to docs/variant_graph_summary.md
            docs_dir = Path(__file__).parent.parent / "docs"
            os.makedirs(docs_dir, exist_ok=True)
            output_file = docs_dir / "variant_graph_summary.md"
            with open(output_file, "w", encoding="utf-8") as f:
                f.write("\n".join(summary_lines) + "\n")
            print(f"\n[INFO] Saved overall aggregated summary to {output_file}")


if __name__ == "__main__":
    asyncio.run(main())
